add_test( [==[Happens Before Graph]==] /home/tanzir/OpenRace/src/bin/tester [==[Happens Before Graph]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Happens_Before_Graph.xml]==])
set_tests_properties( [==[Happens Before Graph]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[HappensBefore Barrier]==] /home/tanzir/OpenRace/src/bin/tester [==[HappensBefore Barrier]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/HappensBefore_Barrier.xml]==])
set_tests_properties( [==[HappensBefore Barrier]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Simple lockset test]==] /home/tanzir/OpenRace/src/bin/tester [==[Simple lockset test]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Simple_lockset_test.xml]==])
set_tests_properties( [==[Simple lockset test]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Construct SharedMemory from real Program]==] /home/tanzir/OpenRace/src/bin/tester [==[Construct SharedMemory from real Program]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Construct_SharedMemory_from_real_Program.xml]==])
set_tests_properties( [==[Construct SharedMemory from real Program]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenMP inSameTeam Analysis]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenMP inSameTeam Analysis]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP_inSameTeam_Analysis.xml]==])
set_tests_properties( [==[OpenMP inSameTeam Analysis]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenMP inSameSingleRegion Analysis]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenMP inSameSingleRegion Analysis]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP_inSameSingleRegion_Analysis.xml]==])
set_tests_properties( [==[OpenMP inSameSingleRegion Analysis]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Manually Constructed IR]==] /home/tanzir/OpenRace/src/bin/tester [==[Manually Constructed IR]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Manually_Constructed_IR.xml]==])
set_tests_properties( [==[Manually Constructed IR]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Builder Read/Write/Call]==] /home/tanzir/OpenRace/src/bin/tester [==[Builder Read/Write/Call]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Builder_Read_Write_Call.xml]==])
set_tests_properties( [==[Builder Read/Write/Call]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Builder pthread create/join]==] /home/tanzir/OpenRace/src/bin/tester [==[Builder pthread create/join]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Builder_pthread_create_join.xml]==])
set_tests_properties( [==[Builder pthread create/join]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Builder pthread mutex]==] /home/tanzir/OpenRace/src/bin/tester [==[Builder pthread mutex]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Builder_pthread_mutex.xml]==])
set_tests_properties( [==[Builder pthread mutex]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( OpenMP /home/tanzir/OpenRace/src/bin/tester OpenMP [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP.xml]==])
set_tests_properties( OpenMP PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Build OpenMP once/end_once IR]==] /home/tanzir/OpenRace/src/bin/tester [==[Build OpenMP once/end_once IR]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Build_OpenMP_once_end_once_IR.xml]==])
set_tests_properties( [==[Build OpenMP once/end_once IR]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Build OpenMP barrier IR]==] /home/tanzir/OpenRace/src/bin/tester [==[Build OpenMP barrier IR]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Build_OpenMP_barrier_IR.xml]==])
set_tests_properties( [==[Build OpenMP barrier IR]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Build OpenMP critical IR]==] /home/tanzir/OpenRace/src/bin/tester [==[Build OpenMP critical IR]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Build_OpenMP_critical_IR.xml]==])
set_tests_properties( [==[Build OpenMP critical IR]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Build OpenMP master IR]==] /home/tanzir/OpenRace/src/bin/tester [==[Build OpenMP master IR]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Build_OpenMP_master_IR.xml]==])
set_tests_properties( [==[Build OpenMP master IR]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( PointerAnalysis /home/tanzir/OpenRace/src/bin/tester PointerAnalysis [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/PointerAnalysis.xml]==])
set_tests_properties( PointerAnalysis PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Duplicate OpenMP Forks]==] /home/tanzir/OpenRace/src/bin/tester [==[Duplicate OpenMP Forks]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Duplicate_OpenMP_Forks.xml]==])
set_tests_properties( [==[Duplicate OpenMP Forks]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( Callstack /home/tanzir/OpenRace/src/bin/tester Callstack [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Callstack.xml]==])
set_tests_properties( Callstack PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[ThreadTrace construction]==] /home/tanzir/OpenRace/src/bin/tester [==[ThreadTrace construction]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/ThreadTrace_construction.xml]==])
set_tests_properties( [==[ThreadTrace construction]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Construct pthread ThreadTrace]==] /home/tanzir/OpenRace/src/bin/tester [==[Construct pthread ThreadTrace]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Construct_pthread_ThreadTrace.xml]==])
set_tests_properties( [==[Construct pthread ThreadTrace]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Nested Pthread ThreadTrace]==] /home/tanzir/OpenRace/src/bin/tester [==[Nested Pthread ThreadTrace]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Nested_Pthread_ThreadTrace.xml]==])
set_tests_properties( [==[Nested Pthread ThreadTrace]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Construct mutex ThreadTrace]==] /home/tanzir/OpenRace/src/bin/tester [==[Construct mutex ThreadTrace]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Construct_mutex_ThreadTrace.xml]==])
set_tests_properties( [==[Construct mutex ThreadTrace]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenmP ThreadTrace construction]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenmP ThreadTrace construction]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenmP_ThreadTrace_construction.xml]==])
set_tests_properties( [==[OpenmP ThreadTrace construction]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[Construct critical ThreadTrace]==] /home/tanzir/OpenRace/src/bin/tester [==[Construct critical ThreadTrace]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/Construct_critical_ThreadTrace.xml]==])
set_tests_properties( [==[Construct critical ThreadTrace]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( pthreadrace /home/tanzir/OpenRace/src/bin/tester pthreadrace [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/pthreadrace.xml]==])
set_tests_properties( pthreadrace PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( dataracebench /home/tanzir/OpenRace/src/bin/tester dataracebench [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/dataracebench.xml]==])
set_tests_properties( dataracebench PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenMP Integration Tests]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenMP Integration Tests]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP_Integration_Tests.xml]==])
set_tests_properties( [==[OpenMP Integration Tests]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenMP Array Index Analysis Integration Tests]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenMP Array Index Analysis Integration Tests]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP_Array_Index_Analysis_Integration_Tests.xml]==])
set_tests_properties( [==[OpenMP Array Index Analysis Integration Tests]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[OpenMP Lock Tests]==] /home/tanzir/OpenRace/src/bin/tester [==[OpenMP Lock Tests]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/OpenMP_Lock_Tests.xml]==])
set_tests_properties( [==[OpenMP Lock Tests]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
add_test( [==[No crash on empty thread]==] /home/tanzir/OpenRace/src/bin/tester [==[No crash on empty thread]==] [==[--reporter junit]==] [==[--out /home/tanzir/OpenRace/src/testresults/No_crash_on_empty_thread.xml]==])
set_tests_properties( [==[No crash on empty thread]==] PROPERTIES WORKING_DIRECTORY /home/tanzir/OpenRace/tests/data)
set( tester_TESTS [==[Happens Before Graph]==] [==[HappensBefore Barrier]==] [==[Simple lockset test]==] [==[Construct SharedMemory from real Program]==] [==[OpenMP inSameTeam Analysis]==] [==[OpenMP inSameSingleRegion Analysis]==] [==[Manually Constructed IR]==] [==[Builder Read/Write/Call]==] [==[Builder pthread create/join]==] [==[Builder pthread mutex]==] OpenMP [==[Build OpenMP once/end_once IR]==] [==[Build OpenMP barrier IR]==] [==[Build OpenMP critical IR]==] [==[Build OpenMP master IR]==] PointerAnalysis [==[Duplicate OpenMP Forks]==] Callstack [==[ThreadTrace construction]==] [==[Construct pthread ThreadTrace]==] [==[Nested Pthread ThreadTrace]==] [==[Construct mutex ThreadTrace]==] [==[OpenmP ThreadTrace construction]==] [==[Construct critical ThreadTrace]==] pthreadrace dataracebench [==[OpenMP Integration Tests]==] [==[OpenMP Array Index Analysis Integration Tests]==] [==[OpenMP Lock Tests]==] [==[No crash on empty thread]==])
